### ISSUE TITLE
simplificar

### ISSUE THREAD

**Issue by santos-fernando** [Deb4cker/25DOOI-Resolucoes-da-monitoria#1]
@Deb4cker 
criar a versão simplificada dos testes do exercicio 1_7 (estudantes); eu fiz essa implementação com a turma em sala, pegar do Moodle e apenas completar as partes faltantes.

**Comment by Deb4cker** [comment]
Bom dia professor! Foi feita a simplificação da classe no ultimo commit: 
[exerc_1_7/EstudanteTest.java](https://github.com/Deb4cker/25DOOI-Resolucoes-da-monitoria/commit/fa1b6ed31fccde56f8191261c312a96e8f69125e#diff-d41676f5bd69316cf307e89574747fdc8788f7165cfebcd5c59c6e3c1b071300)

Vou manter a _issue_ aberta para eventuais melhorias necessárias.

**Comment by Deb4cker** [comment]
Estou finalizando a issue.
