### ISSUE TITLE
implementações faltantes

### ISSUE THREAD

**Issue by santos-fernando** [Deb4cker/25DOOI-Resolucoes-da-monitoria#2]
@Deb4cker 
até sexta 12/4 consegue finalizar e compartilhar os exercícios 1-11, 1-12 e 1-13 da apostila? 
as implementações já disponibilizei com vc no onedrive; teria apenas que implementar os testes adotando como padrão a versão simplificada.

**Comment by Deb4cker** [comment]
Bom dia professor. Todas as implementações faltantes foram feitas no [ultimo commit](https://github.com/Deb4cker/25DOOI-Resolucoes-da-monitoria/commit/fa1b6ed31fccde56f8191261c312a96e8f69125e ).
Vou manter a _issue_ aberta para eventuais melhorias necessárias.

**Comment by Deb4cker** [comment]
Estou finalizando a issue.
